import type { NextPage } from 'next'
import Head from 'next/head'
import HeadNav from '../components/HeadNav/HeadNav'
import Products from '../components/Products/Products'
import MainBanner from '../components/MainBanner'
const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous'/>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet"/>
      </Head>
      <HeadNav/>
      <MainBanner category="Electronics"/>
      <Products/>
    </div>
  )
}

export default Home
