import type { NextPage } from 'next'
import Head from 'next/head'
import HeadNav from '../components/Common/HeadNav'
import Products from '../components/Products/Products'
import MainBanner from '../components/Common/MainBanner'
import Preloader from '../components/Products/Preloader'
import { Suspense } from 'react'
import UserPreloader from '../components/Users/UserPreloader'
const Home: NextPage = () => {
  return (
    <div className="bg-slate-100">
      <Head>
        <title>Aerolab Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<span>Loading user</span>}>
        <UserPreloader/>
        <HeadNav/>
      </Suspense>
      <MainBanner category="Electronics"/>
      <Suspense fallback={<span>Loading products</span>}>
        <Preloader/>
        <Products/>
      </Suspense>
    </div>
  )
}

export default Home
